modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/lukebemish/dynamic_asset_generator/issues"
license = "LGPL v3"

[[mods]]
modId = "dynamic_asset_generator"
version = "${file.jarVersion}"
displayName = "DynamicAssetGenerator"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.dynamic_asset_generator]]
modId = "forge"
mandatory = true
versionRange = "[43.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamic_asset_generator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
