modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/lukebemish/palette_extractor/issues"
license = "LGPL v3"

[[mods]]
modId = "palette_extractor"
version = "${version}"
displayName = "Palette Extractor"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.palette_extractor]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palette_extractor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"