name: Release
concurrency: ci-${{ github.ref }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: tagRelease
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: checkLicenses build prepareJavadoc
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
      - uses: andreiio/rclone-action@v1.2.0
        with:
          args: copy build/prepareJavadoc r2:javadoc-lukebemish-dev
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.JAVADOC_ENDPOINT }}
          RCLONE_CONFIG_R2_ACL: private
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publish curseforge modrinth
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
        env:
          MAVEN_USER: github
          MAVEN_PASSWORD: ${{ secrets.RELEASE_MAVEN_PASSWORD }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          MODRINTH_KEY: ${{ secrets.MODRINTH_KEY }}
          MAVEN_URL: https://maven.lukebemish.dev/releases/
      - run: |
          git push
          git push --tags
